# Generated by Django 2.2.12 on 2021-04-25 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('game_ver', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emoji', models.CharField(default='👓', max_length=10)),
                ('typing', models.NullBooleanField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='earth.GamePlay')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provocation', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(default=1)),
                ('location', models.FloatField()),
                ('text', models.TextField()),
                ('color', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='earth.GamePlay')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='earth.Participant')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='earth.Prompt')),
            ],
        ),
        migrations.AddField(
            model_name='gameplay',
            name='active_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='earth.Prompt'),
        ),
    ]
