# Generated by Django 2.2.12 on 2021-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='location',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
