# Generated by Django 2.2.12 on 2021-05-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0003_auto_20210502_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='location',
            new_name='geo',
        ),
    ]
