# Generated by Django 2.2.12 on 2021-05-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0004_auto_20210502_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earth.Participant'),
        ),
    ]
