# Generated by Django 2.2.12 on 2021-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0006_gameplay_last_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='last_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
