# Generated by Django 2.2.12 on 2021-05-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0007_auto_20210502_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='level',
        ),
        migrations.RemoveField(
            model_name='text',
            name='location',
        ),
        migrations.AddField(
            model_name='prompt',
            name='fill_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='fill_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
