# Generated by Django 2.2.12 on 2021-05-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0008_auto_20210504_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='fill_height',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='fill_length',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='location',
        ),
    ]
