# Generated by Django 2.2.12 on 2021-05-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0010_auto_20210509_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplay',
            old_name='last_location',
            new_name='last_save',
        ),
    ]
