# Generated by Django 2.2.12 on 2021-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0011_auto_20210510_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='queued_energy',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
