# Generated by Django 2.2.12 on 2021-05-13 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0012_participant_queued_energy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='queued_energy',
        ),
        migrations.CreateModel(
            name='EventQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, default='', max_length=20)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='earth.GamePlay')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earth.Participant')),
            ],
        ),
    ]
