# Generated by Django 2.2.12 on 2021-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0014_auto_20210514_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventqueue',
            name='participant',
        ),
        migrations.AddField(
            model_name='eventqueue',
            name='info',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
