# Generated by Django 2.2.12 on 2021-05-14 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0015_auto_20210514_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.CharField(blank=True, default='', max_length=20)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameplay',
            name='last_save',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='typing',
        ),
        migrations.RemoveField(
            model_name='text',
            name='color',
        ),
        migrations.AddField(
            model_name='gameplay',
            name='godot_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='prompt_inner',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='EventQueue',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earth.GamePlay'),
        ),
    ]
