# Generated by Django 2.2.12 on 2021-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0017_auto_20210517_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='event',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
