# Generated by Django 2.2.12 on 2021-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0018_auto_20210517_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='char_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
