# Generated by Django 2.2.12 on 2021-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0019_prompt_char_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
