# Generated by Django 2.2.12 on 2021-05-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0020_text_flag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameLog',
            new_name='XGameLog',
        ),
    ]
